
services:
  geth:
    hostname: geth
    env_file:
      - .env
    image: geth-client
    build:
      context: geth-client
    command:
      --bootnodes="enode://7dea882ad2c14448399130d6d089718381512d01981ed661660510770e27c1c2c02aa32e52835e9f126214b0142c019482fba100110a467766f13f345bd69700@balance_node:30303"
      --nodekey=node.key
      --networkid=${NETWORK_ID}
      --netrestrict=${PROSUMERS_NET}
      --http 
      --http.api db,eth,net,web3,admin,personal,miner,signer:insecure_unlock_protect
      --http.corsdomain="*" 
      --http.addr="0.0.0.0" 
      --http.vhosts=* 
      --password /tmp/password.txt 
      --allow-insecure-unlock 
    networks:
      prosumer-subnet:
      prosumers-net:
  smart-meter:
    hostname: smart-meter
    image: smart-meter
    build:
      context: smart-meter
      args:
        - DATA_FILE=${DATA_FILE}
    networks:
      prosumer-subnet:
  backend-server:
    hostname: backend-server
    image: backend-server
    build:
      context: backend-server
      args:
        - GETH_HOST=${GETH_HOST}
    networks:
      prosumer-subnet:

networks:
  prosumer-subnet:
    driver: bridge
    ipam:
      config:
      - subnet: ${PROSUMER_SUBNET}
  prosumers-net:
    external: true
