
services:
  smart-meter:
    hostname: smart-meter
    image: smart-meter
    build:
      context: smart-meter
      args:
        - DATA_FILE=${DATA_FILE}
        - BACKEND_HOST=${BACKEND_HOST}
    
